use bevy_ecs::{
    system::{HasSystemInput, SystemInput, SystemParam, SystemParamItem, SystemState},
    world::World,
};
use std::marker::PhantomData;
use variadics_please::all_tuples;

pub trait IntoOnceSystem<In: SystemInput, Out, Marker>: Sized {
    fn run_once(self, input: In::Inner<'static>, world: &mut World) -> Out;
}

macro_rules! impl_into_once_system {
    ($($param: ident),*) => {
        #[expect(
            clippy::allow_attributes,
            reason = "This is within a macro and the lint applicability depends on tuple arity."
        )]
        #[allow(
            non_snake_case,
            reason = "Tuple parameter identifiers are generated by macro convention."
        )]
        impl<Out, Func, $($param: SystemParam + 'static),*> IntoOnceSystem<(), Out, fn($($param,)*) -> Out> for Func
        where
            Func: Send + 'static,
            Func: FnOnce($($param),*) -> Out,
            Func: FnOnce($(SystemParamItem<$param>),*) -> Out,
            Out: 'static,
        {
            #[inline]
            fn run_once(self, _input: (), world: &mut World) -> Out {
                fn call_inner<Out, $($param,)*>(
                    f: impl FnOnce($($param,)*) -> Out,
                    $($param: $param,)*
                ) -> Out {
                    f($($param,)*)
                }

                let mut state = SystemState::<($($param,)*)>::new(world);
                let ($($param,)*) = state.get_mut(world);
                let out = call_inner(self, $($param,)*);
                state.apply(world);
                out
            }
        }

        #[expect(
            clippy::allow_attributes,
            reason = "This is within a macro and the lint applicability depends on tuple arity."
        )]
        #[allow(
            non_snake_case,
            reason = "Tuple parameter identifiers are generated by macro convention."
        )]
        impl<In, Out, Func, $($param: SystemParam + 'static),*> IntoOnceSystem<In, Out, (HasSystemInput, fn(In, $($param,)*) -> Out)> for Func
        where
            In: SystemInput + 'static,
            Func: Send + 'static,
            Func: FnOnce(In::Param<'static>, $($param),*) -> Out,
            Func: FnOnce(In::Param<'static>, $(SystemParamItem<$param>),*) -> Out,
            Out: 'static,
        {
            #[inline]
            fn run_once(self, input: In::Inner<'static>, world: &mut World) -> Out {
                fn call_inner<In: SystemInput, Out, $($param,)*>(
                    _: PhantomData<In>,
                    f: impl FnOnce(In::Param<'static>, $($param,)*) -> Out,
                    input: In::Inner<'static>,
                    $($param: $param,)*
                ) -> Out {
                    f(In::wrap(input), $($param,)*)
                }

                let mut state = SystemState::<($($param,)*)>::new(world);
                let ($($param,)*) = state.get_mut(world);
                let out = call_inner(PhantomData::<In>, self, input, $($param,)*);
                state.apply(world);
                out
            }
        }
    };
}

all_tuples!(impl_into_once_system, 0, 16, P);
