use bevy_ecs::{
    error::BevyError,
    system::{SystemParam, SystemParamItem, SystemState},
    world::World,
};
use std::future::Future;
use variadics_please::all_tuples;

use crate::context::task::TaskContext;

/// Trait for closures that can be converted into async systems.
///
/// Two families of implementations:
/// - Without `TaskContext`: `FnOnce(P0, P1, ...) -> Fut`
/// - With `TaskContext`: `FnOnce(TaskContext, P0, P1, ...) -> Fut`
///
/// System parameters are extracted via `SystemState` before calling the closure.
/// The returned future must be `Send + 'static` — clone any params you need
/// in the synchronous preamble before returning the future.
pub trait IntoAsyncSystem<Marker>: Sized + Send + 'static {
    type Future: Future<Output = Result<(), BevyError>> + Send + 'static;
    fn into_future(self, task_context: TaskContext, world: &mut World) -> Self::Future;
}

macro_rules! impl_into_async_system {
    ($($param: ident),*) => {
        // Without TaskContext
        #[expect(
            clippy::allow_attributes,
            reason = "This is within a macro and the lint applicability depends on tuple arity."
        )]
        #[allow(
            non_snake_case,
            reason = "Tuple parameter identifiers are generated by macro convention."
        )]
        impl<Func, Fut, $($param: SystemParam + 'static),*> IntoAsyncSystem<fn($($param,)*) -> Fut> for Func
        where
            Func: Send + 'static,
            Func: FnOnce($($param),*) -> Fut,
            Func: FnOnce($(SystemParamItem<$param>),*) -> Fut,
            Fut: Future<Output = Result<(), BevyError>> + Send + 'static,
        {
            type Future = Fut;

            #[inline]
            fn into_future(self, _task_context: TaskContext, world: &mut World) -> Self::Future {
                fn call_inner<Fut, $($param,)*>(
                    f: impl FnOnce($($param,)*) -> Fut,
                    $($param: $param,)*
                ) -> Fut {
                    f($($param,)*)
                }

                let mut state = SystemState::<($($param,)*)>::new(world);
                let ($($param,)*) = state.get_mut(world);
                let fut = call_inner(self, $($param,)*);
                state.apply(world);
                fut
            }
        }

        // With TaskContext
        #[expect(
            clippy::allow_attributes,
            reason = "This is within a macro and the lint applicability depends on tuple arity."
        )]
        #[allow(
            non_snake_case,
            reason = "Tuple parameter identifiers are generated by macro convention."
        )]
        impl<Func, Fut, $($param: SystemParam + 'static),*> IntoAsyncSystem<fn(TaskContext, $($param,)*) -> Fut> for Func
        where
            Func: Send + 'static,
            Func: FnOnce(TaskContext, $($param),*) -> Fut,
            Func: FnOnce(TaskContext, $(SystemParamItem<$param>),*) -> Fut,
            Fut: Future<Output = Result<(), BevyError>> + Send + 'static,
        {
            type Future = Fut;

            #[inline]
            fn into_future(self, task_context: TaskContext, world: &mut World) -> Self::Future {
                fn call_inner<Fut, $($param,)*>(
                    f: impl FnOnce(TaskContext, $($param,)*) -> Fut,
                    ctx: TaskContext,
                    $($param: $param,)*
                ) -> Fut {
                    f(ctx, $($param,)*)
                }

                let mut state = SystemState::<($($param,)*)>::new(world);
                let ($($param,)*) = state.get_mut(world);
                let fut = call_inner(self, task_context, $($param,)*);
                state.apply(world);
                fut
            }
        }
    };
}

all_tuples!(impl_into_async_system, 0, 16, P);
