use bevy_ecs::{
    system::{HasSystemInput, SystemInput, SystemParam, SystemParamItem, SystemState},
    world::World,
};
use std::marker::PhantomData;
use variadics_please::all_tuples;

use crate::context::main_thread::MainThreadContext;

pub trait IntoOnceSystem<In: SystemInput, Out, Marker>: Sized {
    fn run_once(self, input: In::Inner<'static>, world: &mut World, current_tick: usize) -> Out;
}

macro_rules! impl_into_once_system {
    ($($param: ident),*) => {
        #[expect(
            clippy::allow_attributes,
            reason = "This is within a macro and the lint applicability depends on tuple arity."
        )]
        #[allow(
            non_snake_case,
            reason = "Tuple parameter identifiers are generated by macro convention."
        )]
        impl<Out, Func, $($param: SystemParam + 'static),*> IntoOnceSystem<(), Out, fn($($param,)*) -> Out> for Func
        where
            Func: Send + 'static,
            Func: FnOnce($($param),*) -> Out,
            Func: FnOnce($(SystemParamItem<$param>),*) -> Out,
            Out: 'static,
        {
            #[inline]
            fn run_once(self, _input: (), world: &mut World, _current_tick: usize) -> Out {
                fn call_inner<Out, $($param,)*>(
                    f: impl FnOnce($($param,)*) -> Out,
                    $($param: $param,)*
                ) -> Out {
                    f($($param,)*)
                }

                let mut state = SystemState::<($($param,)*)>::new(world);
                let ($($param,)*) = state.get_mut(world);
                let out = call_inner(self, $($param,)*);
                state.apply(world);
                out
            }
        }

        #[expect(
            clippy::allow_attributes,
            reason = "This is within a macro and the lint applicability depends on tuple arity."
        )]
        #[allow(
            non_snake_case,
            reason = "Tuple parameter identifiers are generated by macro convention."
        )]
        impl<In, Out, Func, $($param: SystemParam + 'static),*> IntoOnceSystem<In, Out, (HasSystemInput, fn(In, $($param,)*) -> Out)> for Func
        where
            In: SystemInput + 'static,
            Func: Send + 'static,
            Func: FnOnce(In::Param<'static>, $($param),*) -> Out,
            Func: FnOnce(In::Param<'static>, $(SystemParamItem<$param>),*) -> Out,
            Out: 'static,
        {
            #[inline]
            fn run_once(self, input: In::Inner<'static>, world: &mut World, _current_tick: usize) -> Out {
                fn call_inner<In: SystemInput, Out, $($param,)*>(
                    _: PhantomData<In>,
                    f: impl FnOnce(In::Param<'static>, $($param,)*) -> Out,
                    input: In::Inner<'static>,
                    $($param: $param,)*
                ) -> Out {
                    f(In::wrap(input), $($param,)*)
                }

                let mut state = SystemState::<($($param,)*)>::new(world);
                let ($($param,)*) = state.get_mut(world);
                let out = call_inner(PhantomData::<In>, self, input, $($param,)*);
                state.apply(world);
                out
            }
        }

        #[expect(
            clippy::allow_attributes,
            reason = "This is within a macro and the lint applicability depends on tuple arity."
        )]
        #[allow(
            non_snake_case,
            reason = "Tuple parameter identifiers are generated by macro convention."
        )]
        impl<Out, Func, $($param: SystemParam + 'static),*> IntoOnceSystem<(), Out, fn(MainThreadContext, $($param,)*) -> Out> for Func
        where
            Func: Send + 'static,
            Func: for<'a> FnOnce(MainThreadContext<'a>, $($param),*) -> Out,
            Func: for<'a> FnOnce(MainThreadContext<'a>, $(SystemParamItem<$param>),*) -> Out,
            Out: 'static,
        {
            #[inline]
            fn run_once(self, _input: (), world: &mut World, current_tick: usize) -> Out {
                fn call_inner<Out, $($param,)*>(
                    f: impl FnOnce(MainThreadContext, $($param,)*) -> Out,
                    ctx: MainThreadContext,
                    $($param: $param,)*
                ) -> Out {
                    f(ctx, $($param,)*)
                }

                let world_ptr = world as *mut World;
                let mut state = SystemState::<($($param,)*)>::new(world);
                let ($($param,)*) = state.get_mut(world);
                let out = call_inner(
                    self,
                    // SAFETY: This preserves prior API behavior where callbacks may use both
                    // context and system params in one closure on the main thread.
                    MainThreadContext { world: unsafe { &mut *world_ptr }, current_tick },
                    $($param,)*
                );
                state.apply(world);
                out
            }
        }

        #[expect(
            clippy::allow_attributes,
            reason = "This is within a macro and the lint applicability depends on tuple arity."
        )]
        #[allow(
            non_snake_case,
            reason = "Tuple parameter identifiers are generated by macro convention."
        )]
        impl<In, Out, Func, $($param: SystemParam + 'static),*> IntoOnceSystem<In, Out, (HasSystemInput, fn(In, MainThreadContext, $($param,)*) -> Out)> for Func
        where
            In: SystemInput + 'static,
            Func: Send + 'static,
            Func: for<'a> FnOnce(In::Param<'static>, MainThreadContext<'a>, $($param),*) -> Out,
            Func: for<'a> FnOnce(In::Param<'static>, MainThreadContext<'a>, $(SystemParamItem<$param>),*) -> Out,
            Out: 'static,
        {
            #[inline]
            fn run_once(self, input: In::Inner<'static>, world: &mut World, current_tick: usize) -> Out {
                fn call_inner<In: SystemInput, Out, $($param,)*>(
                    _: PhantomData<In>,
                    f: impl FnOnce(In::Param<'static>, MainThreadContext, $($param,)*) -> Out,
                    input: In::Inner<'static>,
                    ctx: MainThreadContext,
                    $($param: $param,)*
                ) -> Out {
                    f(In::wrap(input), ctx, $($param,)*)
                }

                let world_ptr = world as *mut World;
                let mut state = SystemState::<($($param,)*)>::new(world);
                let ($($param,)*) = state.get_mut(world);
                let out = call_inner(
                    PhantomData::<In>,
                    self,
                    input,
                    // SAFETY: See the matching MainThreadContext + params implementation above.
                    MainThreadContext { world: unsafe { &mut *world_ptr }, current_tick },
                    $($param,)*
                );
                state.apply(world);
                out
            }
        }
    };
}

all_tuples!(impl_into_once_system, 0, 16, P);
